name: test-all
on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
    tags-ignore:
      - 'v*' #avoids rerun existing commit on release
  pull_request:
    branches:
      - 'main'

permissions:
  packages: write

jobs:
  test-java:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: java
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
      - name: Select Java Version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'

      - name: Build and test
        run: mvn deploy -Dmaven.test.failure.ignore=true -U --no-transfer-progress
