name: test-all
on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
    tags-ignore:
      - 'v*' #avoids rerun existing commit on release
  pull_request:
    branches:
      - 'main'
  workflow_dispatch: #allow manual run
  
permissions:
  contents: read
  packages: write

jobs:
  test-java:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: java
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
      - name: Select Java Version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Build and test
        run: mvn test -Dmaven.test.failure.ignore=true -U --no-transfer-progress

  publish-java-snapshot:
    #avoid publishing PRs and dependabot branches
    if: ${{ github.event_name != 'pull_request' && !contains('/head/refs/dependabot/', github.ref) && !contains('/head/refs/dashgit/combined/', github.ref) }}
    runs-on: ubuntu-latest
    steps:
      # NOTE: deploy args use the profile `publish-github` that specifies the github repository server (see pom.xml)
      - uses: javiertuya/branch-snapshots-action@v1.1.0
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          java-version: '8'
          mvn-deploy-args: '-P publish-github -DskipTests=true -Dmaven.test.failure.ignore=false -U --no-transfer-progress'
          delete-old-snapshots: true
          min-snapshots-to-keep: 4
